options {
  directory "/var/cache/bind";
  listen-on { any; };
  listen-on-v6 { none; };
  allow-query { any; };
  recursion no;
};
zone "oscp.local" {
  type master;
  file "/etc/bind/db.oscp.local";
};

zone "77.31.172.in-addr.arpa" {
  type master;
  file "/etc/bind/db.172.31.77";
};
