[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
[program:sshd]
command=/usr/sbin/sshd -D -e
priority=10
[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=20
[program:smbd]
command=/usr/sbin/smbd --foreground --no-process-group
priority=30
[program:nmbd]
command=/usr/sbin/nmbd --foreground --no-process-group
priority=31
[program:snmpd]
command=/usr/sbin/snmpd -f -Lo
priority=40

[program:iteh-smtp]
command=/usr/bin/python3 /opt/iteh/smtp_server.py
priority=55
autorestart=true
